// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "restaurants",
    columns: [
      { name: "shopName", type: "string" },
      { name: "shopAddress", type: "string" },
      { name: "shopImg", type: "string" },
      { name: "shopOpenTime", type: "string" },
      { name: "shopCloseTime", type: "string" },
      { name: "user_id", type: "string" },
    ],
  },
  {
    name: "orders",
    columns: [
      { name: "order_imgUrl", type: "string" },
      { name: "order_price", type: "int" },
      { name: "order_name", type: "string" },
      { name: "order_description", type: "string" },
    ],
  },
  {
    name: "user",
    columns: [
      { name: "user_id", type: "string" },
      { name: "address", type: "string" },
      { name: "city", type: "string" },
      { name: "country", type: "string" },
    ],
  },
  {
    name: "dishes",
    columns: [
      { name: "dishName", type: "string" },
      { name: "dishDescription", type: "string" },
      { name: "dishPhoto", type: "string" },
      { name: "dishPrice", type: "int" },
      { name: "restaurant_id", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Restaurants = InferredTypes["restaurants"];
export type RestaurantsRecord = Restaurants & XataRecord;

export type Orders = InferredTypes["orders"];
export type OrdersRecord = Orders & XataRecord;

export type User = InferredTypes["user"];
export type UserRecord = User & XataRecord;

export type Dishes = InferredTypes["dishes"];
export type DishesRecord = Dishes & XataRecord;

export type DatabaseSchema = {
  restaurants: RestaurantsRecord;
  orders: OrdersRecord;
  user: UserRecord;
  dishes: DishesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Ralph-Codes-s-workspace-uglabh.us-east-1.xata.sh/db/food",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
